In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.array([1,2,3,4,5,"sudh", 34+8j])

array(['1', '2', '3', '4', '5', 'sudh', '(34+8j)'], dtype='<U64')

In [6]:
np.array([1,2,3,4.5,6.0])

array([1. , 2. , 3. , 4.5, 6. ])

In [7]:
np.array([[3,4],[3,4]])

array([[3, 4],
       [3, 4]])

In [8]:
np.array([[3,4],[3,4],[6,7]])

array([[3, 4],
       [3, 4],
       [6, 7]])

In [10]:
np.array([[3,4],[3,4],[6,7,8]])

C:\Users\MUHAMM~1\AppData\Local\Temp/ipykernel_16208/4169081146.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[3,4],[3,4],[6,7,8]])


array([list([3, 4]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [11]:
np.array([[[3,4],[3,4]], [[3,4],[3,4]]])

array([[[3, 4],
        [3, 4]],

       [[3, 4],
        [3, 4]]])

In [12]:
np.array([1,2,3], ndmin = 3)

array([[[1, 2, 3]]])

In [13]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [16]:
arr = np.array([(1,2),(3,4)], dtype = [('a', '<i4'), ('b', '<i8')])
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])

In [17]:
arr[0]

(1, 2)

In [19]:
type(arr[0][0])

numpy.int32

In [20]:
type(arr[0][1])

numpy.int64

In [22]:
arr = np.array([[1,3],[3,4]])

In [23]:
arr

array([[1, 3],
       [3, 4]])

In [24]:
arr[0]

array([1, 3])

In [25]:
arr[0][1]

3

In [26]:
arr[1][0]

3

In [27]:
type(arr[1][0])

numpy.int32

In [28]:
np.mat(arr)

matrix([[1, 3],
        [3, 4]])

In [34]:
mat = np.matrix(arr)

In [30]:
l= [3,4,5,6,7]

In [31]:
np.array(l)

array([3, 4, 5, 6, 7])

In [32]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [33]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [35]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [36]:
np.asarray(mat)

array([[1, 3],
       [3, 4]])

In [37]:
issubclass(np.matrix, np.ndarray)

True

In [38]:
issubclass(np.ndarray, np.matrix)

False

In [39]:
arr

array([[1, 3],
       [3, 4]])

In [40]:
a= arr  # Shallow Copy

In [41]:
b = np.copy(arr)  # Deep Copy

In [42]:
arr[0][0] = 67

In [43]:
arr

array([[67,  3],
       [ 3,  4]])

In [44]:
a

array([[67,  3],
       [ 3,  4]])

In [45]:
b

array([[1, 3],
       [3, 4]])

In [46]:
arr[0:10]

array([[67,  3],
       [ 3,  4]])

In [47]:
arr[-1]

array([3, 4])

In [48]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [49]:
np.fromfunction(lambda i, j : i==j , (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [50]:
np.fromfunction(lambda i, j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [51]:
np.fromfunction(lambda i, j : i**j , (3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [52]:
np.fromfunction(lambda i, j : i/j , (3,3))

C:\Users\MUHAMM~1\AppData\Local\Temp/ipykernel_16208/2384961357.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j : i/j , (3,3))
C:\Users\MUHAMM~1\AppData\Local\Temp/ipykernel_16208/2384961357.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j : i/j , (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [59]:
gen = (i*i for i in range(5))

In [57]:
def test(x):
    yield x

In [58]:
test(5)

<generator object test at 0x000001F51B00A740>

In [60]:
gen

<generator object <genexpr> at 0x000001F51B00A820>

In [61]:
np.fromiter(gen, dtype = int)

array([ 0,  1,  4,  9, 16])

In [62]:
np.fromiter(range(5), dtype = int)

array([0, 1, 2, 3, 4])

In [63]:
np.fromstring('1,34,45,6,54', sep =',', dtype = int)

array([ 1, 34, 45,  6, 54])

In [64]:
np.fromstring('1 34 45 6 54', sep =' ', dtype = complex)

array([ 1.+0.j, 34.+0.j, 45.+0.j,  6.+0.j, 54.+0.j])

In [65]:
l = [3,4,5,6,7,8]

In [67]:
arr = np.array(l)

In [70]:
arr1 = np.array([[1,2,3,4], [2,3,4,5], [3,4,5,6]])

In [72]:
type(arr1)

numpy.ndarray

In [73]:
arr1.ndim

2

In [74]:
arr1.size

12

In [75]:
arr1.shape

(3, 4)

In [76]:
arr1.dtype

dtype('int32')

In [77]:
arr.size

6

In [78]:
arr.ndim

1

In [79]:
arr.shape

(6,)

In [82]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]], [[1,2,3,4],[4,5,6,7]]])

In [83]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [84]:
arr2.size

16

In [88]:
arr2.shape # 2 array of 2 x 4

(2, 2, 4)

In [89]:
arr2.ndim

3

In [90]:
arr3 = np.array([[[[1,2,3,4],[4,5,6,7]], [[1,2,3,4],[4,5,6,7]], [[1,2,3,4],[4,5,6,7]], [[1,2,3,4],[4,5,6,7]]]])

In [91]:
arr3

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [92]:
arr3.ndim

4

In [93]:
arr3.shape

(1, 4, 2, 4)

In [94]:
arr3.size

32

In [99]:
list(range(6.6,9,.3))

TypeError: 'float' object cannot be interpreted as an integer

In [98]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [100]:
np.arange(6.6,9,0.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [102]:
np.arange(9,6.6,-0.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [103]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [104]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [107]:
np.linspace(1,2,5) # Generate evenly space data between intervals

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [108]:
np.linspace(.3,.22,10)

array([0.3       , 0.29111111, 0.28222222, 0.27333333, 0.26444444,
       0.25555556, 0.24666667, 0.23777778, 0.22888889, 0.22      ])

In [109]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [115]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [117]:
np.ones(4)

array([1., 1., 1., 1.])

In [118]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [119]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [120]:
np.ones((2,3,1)) + 5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [121]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [123]:
np.empty((3,4))

array([[1.06331751e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 2.95642517e-032, 2.87822983e+180,
        6.87035177e+169],
       [4.04754618e-037, 3.34797066e-033, 1.16087559e-046,
        2.62662507e+179]])

In [126]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [130]:
np.linspace(2,4,4, endpoint = False, axis =0 )

array([2. , 2.5, 3. , 3.5])

In [131]:
np.linspace([1,6],4, endpoint = False, axis =1 )

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [132]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [133]:
np.logspace([2,3],4, axis =1)

array([[  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
          145.63484775,   159.98587196,   175.75106249,   193.06977289,
          212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
          308.88435965,   339.32217719,   372.75937203,   409.49150624,
          449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
          655.12855686,   719.685673  ,   790.60432109,   868.51137375,
          954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
         1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
         2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
         2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
         4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
         6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
         9102.98177992, 10000.        ],
       [ 1000.        ,  1048.11313415,  1098.54114199,  1151.39539933,
         1206.79264064,

In [134]:
d = np.linspace(4,7,40)
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [135]:
d.ndim

1

In [136]:
d.shape

(40,)

In [137]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [138]:
d.reshape(1,2,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [139]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [140]:
np.random.rand(3)

array([0.98846086, 0.57622334, 0.56474431])

In [141]:
np.random.randn(5)

array([ 0.62384781, -0.05488365, -0.12281023,  0.72391625, -0.64944783])

In [142]:
np.random.randn(2,3)

array([[-0.42075599,  0.33552229, -0.90670659],
       [ 1.99315079,  0.03172596,  0.43738617]])

In [147]:
np.random.randn(3,3,3)

array([[[-0.25650162,  0.2829913 , -0.33007675],
        [-0.15045148, -1.65717068, -0.47408663],
        [ 0.964968  ,  1.82491049, -0.9236601 ]],

       [[ 0.61271986, -0.04190568,  0.98009234],
        [ 0.32431993, -0.16532656,  1.82851561],
        [ 0.14107524, -0.63842527, -0.34427984]],

       [[ 0.52339627,  0.48440331,  2.08706052],
        [-1.13355586,  0.42271172, -2.02872082],
        [ 0.24951999, -1.8291287 ,  2.19207397]]])

In [150]:
np.random.randint(5)

3

In [151]:
np.random.randint(5,60)

28

In [152]:
np.random.randint(5,60, (4,4))

array([[27, 52, 21, 56],
       [10, 28, 29, 36],
       [20, 43, 33, 37],
       [ 6, 23, 37, 29]])

In [153]:
arr = np.random.randint(3,9, (3,3))

In [154]:
arr

array([[4, 4, 3],
       [7, 5, 6],
       [4, 3, 4]])

In [155]:
arr.reshape(1,9)

array([[4, 4, 3, 7, 5, 6, 4, 3, 4]])

In [156]:
arr.reshape(9,1)

array([[4],
       [4],
       [3],
       [7],
       [5],
       [6],
       [4],
       [3],
       [4]])

In [157]:
arr.reshape(1,1,9)

array([[[4, 4, 3, 7, 5, 6, 4, 3, 4]]])

In [158]:
arr.reshape(3,3,1)

array([[[4],
        [4],
        [3]],

       [[7],
        [5],
        [6]],

       [[4],
        [3],
        [4]]])

In [159]:
arr.reshape(3,-1) # negative will take automatic value of matrix

array([[4, 4, 3],
       [7, 5, 6],
       [4, 3, 4]])

In [161]:
arr.reshape(1,-143434)

array([[4, 4, 3, 7, 5, 6, 4, 3, 4]])

In [162]:
arr

array([[4, 4, 3],
       [7, 5, 6],
       [4, 3, 4]])

In [164]:
arr.max()

7

In [165]:
arr.min()

3

In [168]:
arr = np.random.randint(4,100, (5,5))

In [169]:
arr

array([[65, 32, 43, 96, 84],
       [42, 89, 93, 59, 60],
       [77, 10, 17, 34, 97],
       [33, 98, 78, 84, 67],
       [52, 15, 89, 20, 87]])

In [170]:
arr[3: , 3: ]

array([[84, 67],
       [20, 87]])

In [173]:
arr[: , [1,3]]

array([[32, 96],
       [89, 59],
       [10, 34],
       [98, 84],
       [15, 20]])

In [174]:
arr

array([[65, 32, 43, 96, 84],
       [42, 89, 93, 59, 60],
       [77, 10, 17, 34, 97],
       [33, 98, 78, 84, 67],
       [52, 15, 89, 20, 87]])

In [175]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [177]:
arr[arr>10]

array([65, 32, 43, 96, 84, 42, 89, 93, 59, 60, 77, 17, 34, 97, 33, 98, 78,
       84, 67, 52, 15, 89, 20, 87])

In [178]:
arr

array([[65, 32, 43, 96, 84],
       [42, 89, 93, 59, 60],
       [77, 10, 17, 34, 97],
       [33, 98, 78, 84, 67],
       [52, 15, 89, 20, 87]])

In [179]:
arr*arr

array([[4225, 1024, 1849, 9216, 7056],
       [1764, 7921, 8649, 3481, 3600],
       [5929,  100,  289, 1156, 9409],
       [1089, 9604, 6084, 7056, 4489],
       [2704,  225, 7921,  400, 7569]])

In [180]:
arr1 = np.random.randint(2,4,(3,3))

In [182]:
arr2 = np.random.randint(2,5,(3,3))

In [183]:
arr1

array([[2, 3, 2],
       [2, 2, 2],
       [3, 2, 3]])

In [184]:
arr2

array([[2, 4, 2],
       [2, 3, 3],
       [4, 4, 2]])

In [192]:
arr1*arr2  #index multiplication

array([[ 4, 12,  4],
       [ 4,  6,  6],
       [12,  8,  6]])

In [193]:
arr3 = np.random.randint(2,5,(2,3))

In [194]:
arr3

array([[4, 4, 4],
       [2, 3, 2]])

In [195]:
arr1*arr3

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [196]:
arr3@arr1  # Matrix Multiplication

array([[28, 28, 28],
       [16, 16, 16]])

In [197]:
arr/0

C:\Users\MUHAMM~1\AppData\Local\Temp/ipykernel_16208/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [198]:
arr**2

array([[4225, 1024, 1849, 9216, 7056],
       [1764, 7921, 8649, 3481, 3600],
       [5929,  100,  289, 1156, 9409],
       [1089, 9604, 6084, 7056, 4489],
       [2704,  225, 7921,  400, 7569]], dtype=int32)

In [199]:
arr5 = np.zeros((3,4))

In [201]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [203]:
a = np.array([1,2,3,4])

In [204]:
a

array([1, 2, 3, 4])

In [205]:
a + arr5

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [206]:
arr5 + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [207]:
b = np.array([1,2,3])

In [208]:
arr5 + b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [213]:
c = np.array([5,6,7])
c

array([5, 6, 7])

In [214]:
c.reshape(3,1) 

array([[5],
       [6],
       [7]])

In [215]:
c.reshape(3,1) + arr5

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [216]:
c = np.array([[5,6,7]])
c

array([[5, 6, 7]])

In [217]:
c.T  #Transpose

array([[5],
       [6],
       [7]])

In [218]:
c.T + arr5

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [219]:
arr = np.random.rand(5,4)

In [220]:
arr

array([[0.41467454, 0.34945583, 0.98424886, 0.46114021],
       [0.34968891, 0.41920903, 0.44454161, 0.65450883],
       [0.23373218, 0.37386752, 0.1747334 , 0.9515982 ],
       [0.5623381 , 0.58617837, 0.04518389, 0.67339491],
       [0.46150146, 0.235809  , 0.20220104, 0.9100502 ]])

In [222]:
np.sqrt(arr)

array([[0.64395228, 0.59114789, 0.99209317, 0.67907305],
       [0.591345  , 0.64746354, 0.66673954, 0.8090172 ],
       [0.48345856, 0.61144707, 0.41801124, 0.97549895],
       [0.74989206, 0.76562287, 0.21256503, 0.82060643],
       [0.67933899, 0.48560169, 0.4496677 , 0.95396551]])

In [223]:
np.exp(arr)

array([[1.51387795, 1.41829554, 2.67580123, 1.58588118],
       [1.41862616, 1.52075821, 1.55977505, 1.92419718],
       [1.2633061 , 1.45334459, 1.19092867, 2.58984545],
       [1.75477053, 1.7971074 , 1.04622024, 1.96088305],
       [1.5864542 , 1.26593249, 1.22409408, 2.48444725]])

In [228]:
np.log2(arr)

array([[-1.26994863, -1.516818  , -0.02290496, -1.11672264],
       [-1.51585606, -1.25425829, -1.16960962, -0.61151543],
       [-2.09707174, -1.41940097, -2.5167727 , -0.07157555],
       [-0.83049031, -0.77058835, -4.46804758, -0.57047528],
       [-1.11559288, -2.08430933, -2.30613767, -0.13598196]])

In [226]:
arr6 = np.random.randint(2,5,(5,5))

In [227]:
np.log10(arr6)

array([[0.60205999, 0.47712125, 0.47712125, 0.47712125, 0.60205999],
       [0.47712125, 0.30103   , 0.60205999, 0.60205999, 0.47712125],
       [0.30103   , 0.30103   , 0.60205999, 0.47712125, 0.60205999],
       [0.60205999, 0.30103   , 0.30103   , 0.30103   , 0.60205999],
       [0.30103   , 0.47712125, 0.47712125, 0.60205999, 0.60205999]])

In [233]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])